version: '3.8'

services:
  app:
    container_name: money-tracking-app
    build:
      context: "."
      dockerfile: Dockerfile
    image: "money-tracking-app"
    command: go run main.go
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./:/app
    networks:
      - mta-network

  database:
    container_name: mta-database
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mta-network

networks:
  mta-network:
    name: mta-network
    driver: bridge
