// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package data

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int32
	Type      string
	Name      string
	Icon      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID         int32
	WalletID   int32
	CategoryID int32
	Nominal    sql.NullInt64
	DateTime   sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Wallet struct {
	ID        int32
	Name      string
	Icon      sql.NullString
	Currency  string
	Balance   sql.NullInt64
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
